[project]
name = "vis-corr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "loguru>=0.7.3",
    "numpy>=2.4.1",
    "open3d>=0.19.0",
    "plyfile>=1.1.3",
    "scikit-image>=0.26.0",
]
